version: '3'
services:
  nginx:
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    depends_on:
      - client
    ports:
      - "3050:80"
  api:
    restart: on-failure
    build:
      dockerfile: Dockerfile.dev
      context: ./api
    environment:
      - NODE_ENV=development
      - ENV=local
      - POSTGRES_DB=${PGDATABASE}
      - POSTGRES_PASSWORD=${PGPASSWORD}
      - REDISPORT=${REDISPORT}
      - REDISHOST=${REDISHOST}
    depends_on:
      - postgres
      - redis
    ports:
      - "8080:8080"
    volumes:
      - ./api:/app
      - /app/node_modules
  client:
    build:
      dockerfile: Dockerfile.dev
      context: ./client
    ports:
      - "4200:4200"
    volumes:
      - ./client:/app
      - /app/node_modules
  postgres:
    image: 'postgres:latest'
    ports:
      - 6432:5432
    environment:
      - POSTGRES_PASSWORD=${PGPASSWORD}
      - POSTGRES_DB=${PGDATABASE}
      - PGDATA= /tmp
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
  redis:
    image: redis:latest
    volumes:
      - ./data/redis:/data
    ports:
      - 6380:6379

volumes:
  postgres-data:
    external: true